%{

/* include files and global decls go here */
#include <stdio.h>

%}

%token id num

%%

S: E
	;

E: T EP
	;

EP: '+' T EP
	| '-' T EP
	|
	;

T: F TP
	;

TP: '*' F TP
	| '/' F TP
	|
	;

F: id
	| num
	| '(' E ')'
	;

%%

//
int yylex()
{
}

//
int main()
{
}